name: Github build

on:
  pull_request:
    branches:
      - 'develop'
      - 'master'
      
jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 10
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16'

      - name: Create new artifact branch
        run:
          git checkout -b UI_WORKFLOW/$GITHUB_REF_NAME

      - name: NPM Install node_modules
        run: |
          cd /myd10project/web/themes/custom/sample_subtheme
          npm install

      - name: Compile CSS from SCSS files
        run: |
          cd /myd10project/web/themes/custom/sample_subtheme
          npx gulp compileSass
