name: Github build

on:
  pull_request:
    branches:
      - 'develop'
      - 'master'
      - 'qa'
      - 'workflowtest'

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 10
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16'

      - name: Create new artifact branch
        run:
          git checkout -b WORKFLOW/$GITHUB_REF_NAME

      - name: NPM Install node_modules
        run: |
          cd /arkjoseph/myd10project/web/themes/custom/sample_subtheme
          npm install

      - name: Compile CSS from SCSS files
        run: |
          cd /arkjoseph/myd10project/web/themes/custom/sample_subtheme
          npx gulp compileSass

#      - name: Branch handling prep for deployment to expose CSS to the remote for saving.
#        run: rm -f ./drupal/web/themes/custom/uswds_base_fai/.gitignore

#      - name: Isolate the build artifacts from the main branches, so they are only exposed to Jenkins.
#        run: |
#          git config --local user.email 'action@github.com'
#          git config --local user.name 'GitHub Action'
#          git add -f ./drupal/web/themes/custom/uswds_base_fai/css/*
#          git add -f ./drupal/web/themes/custom/uswds_base_fai/package.json
#          git add -f ./drupal/web/themes/custom/uswds_base_fai/package-lock.json
#          git commit -m "CSS Compiled by GitHub Workflow build_css.yml. Commit SHA $GITHUB_SHA"
#          git push origin WORKFLOW/$GITHUB_REF_NAME -f
