name: Github build

on:
  pull_request:
    branches:
      - 'develop'
      - 'master'
      - 'qa'
      - 'workflowtest'

jobs:
  build_css:
    # Runner Name
    runs-on: ubuntu-latest

    steps:
      # Checks-out repo for job
      - uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 10
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16'

      - name: Create new artifact branch
        run:
          git checkout -b WORKFLOW/$GITHUB_REF_NAME

      - name: Install and run gulp
        working-directory: '/home/runner/work/myd10project/myd10project/web/themes/custom/sample_subtheme'
        run:
          npm install;
          echo "Done! Compile and delete gitignore for deployment process";
          npx gulp compileSass;
          rm -f .gitignore;

      - name: Git setup for new commit
        run:
          git config --local user.email 'action@github.com';
          git config --local user.name 'GitHub Action';
          git add -A;
          git commit -am "Theme compiled - $GITHUB_SHA";

      - name: Run Style Linter
        run:
          npm install stylelint stylelint-scss --save-dev;
          npx stylelint 'sass/**/*.scss' --quiet || echo "Linting errors found, but build continues"

      - name: Push changes
        run:
          git push origin WORKFLOW/$GITHUB_REF_NAME -f

      - name: Run custom module code checks
        working-directory: '/home/runner/work/myd10project/myd10project/'
        run:
          composer require --dev "squizlabs/php_codesniffer=*";
          vendor/bin/phpcs --standard=PSR2 --ignore="vendor/*" . || echo "PHP code sniffing errors found, but build continues"

#         - name: Isolate the build artifacts from the main branches, so they are only exposed to Jenkins.
#        run:
#          uses: ad-m/github-push-action@develop
#          with:
#            github_token: ${{ secrets.GITHUB_TOKEN }}
#          git config --local user.email 'action@github.com'
#          git config --local user.name 'GitHub Action'
#          git add -f ./drupal/web/themes/custom/uswds_base_fai/css/*
#          git add -f ./drupal/web/themes/custom/uswds_base_fai/package.json
#          git add -f ./drupal/web/themes/custom/uswds_base_fai/package-lock.json
#          git commit -m "CSS Compiled by GitHub Workflow build_css.yml. Commit SHA $GITHUB_SHA"
#          git push origin WORKFLOW/$GITHUB_REF_NAME -f
